name: build and publish imgs workflow

on:
  workflow_call:
    inputs:
      push:
        required: true
        type: boolean

jobs:
  docker:
    name: rapidsai/manylinux ${{ matrix.labels[2] }}
    runs-on: ${{ matrix.labels }}
    strategy:
      matrix:
        include:
          - labels: [self-hosted, linux, amd64, cpu4]
            cpu-arch: x86_64
            rhel-cuda-repo: http://developer.download.nvidia.com/compute/cuda/repos/rhel8/x86_64/cuda-rhel8.repo
          - labels: [self-hosted, linux, arm64, cpu4]
            cpu-arch: aarch64
            rhel-cuda-repo: http://developer.download.nvidia.com/compute/cuda/repos/rhel8/sbsa/cuda-rhel8.repo
    env:
      DOCKERHUB_USERNAME: ${{ secrets.GPUCIBOT_DOCKERHUB_USER }}
      DOCKERHUB_TOKEN: ${{ secrets.GPUCIBOT_DOCKERHUB_TOKEN }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - if: ${{ env.DOCKERHUB_USERNAME != '' && env.DOCKERHUB_TOKEN != '' }}
        name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ env.DOCKERHUB_USERNAME }}
          password: ${{ env.DOCKERHUB_TOKEN }}
      - name: Build rapidsai/manylinux containers
        run: >
          docker build
          -f Dockerfile
          --build-arg CPU_ARCH=${{ matrix.cpu-arch }}
          --build-arg RHEL_CUDA_REPO=${{ matrix.rhel-cuda-repo }}
          -t rapidsai/manylinux:${{ matrix.labels[2] }}
          --pull
          .
      - name: Push rapidsai/manylinux containers to DockerHub
        if: ${{ inputs.push }}
        run: >
          docker push rapidsai/manylinux:${{ matrix.labels[2] }}
