name: build and publish imgs workflow

on:
  workflow_call:
    inputs:
      push:
        required: true
        type: boolean

jobs:
  docker:
    runs-on: ubuntu-latest
    env:
      DOCKERHUB_USERNAME: ${{ secrets.GPUCIBOT_DOCKERHUB_USER }}
      DOCKERHUB_TOKEN: ${{ secrets.GPUCIBOT_DOCKERHUB_TOKEN }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - if: ${{ env.DOCKERHUB_USERNAME != '' && env.DOCKERHUB_TOKEN != '' }}
        name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ env.DOCKERHUB_USERNAME }}
          password: ${{ env.DOCKERHUB_TOKEN }}
      - name: Build and push manylinux for amd64
        timeout-minutes: 30
        uses: docker/build-push-action@v3
        with:
          file: Dockerfile
          platforms: 'linux/amd64'
          push: ${{ inputs.push }}
          pull: true
          build-args: |
            CPU_ARCH=x86_64
            RHEL_CUDA_REPO=http://developer.download.nvidia.com/compute/cuda/repos/rhel8/x86_64/cuda-rhel8.repo
          tags: rapidsai/manylinux:amd64
      - name: Build and push manylinux arm64
        timeout-minutes: 30
        uses: docker/build-push-action@v3
        with:
          file: Dockerfile
          platforms: 'linux/arm64'
          push: ${{ inputs.push }}
          pull: true
          build-args: |
            CPU_ARCH=aarch64
            RHEL_CUDA_REPO=http://developer.download.nvidia.com/compute/cuda/repos/rhel8/sbsa/cuda-rhel8.repo
          tags: rapidsai/manylinux:arm64
